name: pull request

on:
  pull_request:
    branches: [ develop ]

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
    steps:
    - name: Setup .NET Core if needed
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: 3.1.100
      if: matrix.os == 'macOS-latest' || matrix.os == 'ubuntu-latest'
    - uses: actions/checkout@v2
    - name: Restore with dotnet
      run: dotnet restore ./Quiz.sln
    - name: Build with dotnet
      run: dotnet build ./Quiz.sln --configuration Release --no-restore
    - name: Test with dotnet
      run: dotnet test ./Quiz.sln --configuration Release --no-build
